name: Register device and build iOS internal

on:
  pull_request_labeled:
    labels: ["add-ios-device"]

jobs:
  register_device:
    type: apple-device-registration-request
    params:
      apple_team_identifier: CB8EP95D83
  build_ios:
    needs: [register_device]
    type: build
    params:
      platform: ios
      profile: developmemt
      refresh_ad_hoc_provisioning_profile: true
